inherit_from: .rubocop_todo.yml
plugins:
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  AllowedVariables:
    - $CXXFLAGS
Metrics/CyclomaticComplexity:
  Max: 10
